from quad_controller_rl.agents.base_agent import BaseAgent
from quad_controller_rl.agents.policy_search import RandomPolicySearch
from quad_controller_rl.agents.Takeoff_agent import TakeOffAgent
from quad_controller_rl.agents.Hover_agent import HoverAgent
from quad_controller_rl.agents.Landing_agent import LandingAgent
from quad_controller_rl.agents.DDPG import DDPG_Agent